Fixed issue with aliasing

diff --git a/.github/workflows/deploy-lambda-python.yml b/.github/workflows/deploy-lambda-python.yml
--- a/.github/workflows/deploy-lambda-python.yml
+++ b/.github/workflows/deploy-lambda-python.yml
@@ -62,12 +62,6 @@ jobs:
         run: |
           pipenv install --deploy --ignore-pipfile
 
-      - name: Generate requirements.txt
-        run: pipenv run pip freeze > requirements.txt
-
-      - name: Freeze and install dependencies
-        run: pip install -r requirements.txt -t .
-
       - name: Package Lambda and dependencies
         run: |
           pipenv run pip freeze | xargs pip install --no-cache-dir -t .
@@ -90,16 +84,24 @@ jobs:
             --s3-bucket ${{ secrets.S3_BUCKET }} \
             --s3-key ${{ secrets.FUNCTION_NAME }}/${{ needs.prepare.outputs.sha }}.zip
 
-      - name: Waiting for Lambda to update...
+      - name: Wait for Lambda update to complete
         run: |
           aws lambda wait function-updated \
             --function-name ${{ secrets.FUNCTION_NAME }}
 
-      - name: Update Lambda Alias
+      - name: Update or Create Lambda Alias
         if: ${{ vars.VERSION_ALIAS }}
         run: |
           version=$(aws lambda publish-version --function-name ${{ secrets.FUNCTION_NAME }} --query 'Version' --output text)
-          aws lambda update-alias \
-            --function-name ${{ secrets.FUNCTION_NAME }} \
-            --name ${{ vars.VERSION_ALIAS }} \
-            --function-version $version
+          alias_exists=$(aws lambda get-alias --function-name ${{ secrets.FUNCTION_NAME }} --name ${{ vars.VERSION_ALIAS }} 2>&1 || true)
+          if echo "$alias_exists" | grep -q 'Alias not found'; then
+            aws lambda create-alias \
+              --function-name ${{ secrets.FUNCTION_NAME }} \
+              --name ${{ vars.VERSION_ALIAS }} \
+              --function-version $version
+          else
+            aws lambda update-alias \
+              --function-name ${{ secrets.FUNCTION_NAME }} \
+              --name ${{ vars.VERSION_ALIAS }} \
+              --function-version $version
+          fi
